In [44]:
import numpy as np
import pandas as pd
from pandas_datareader import data, wb
import datetime
from dateutil.relativedelta import relativedelta
import matplotlib.pyplot as plt
from pandas import datetime
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split
import warnings
import plotly.express as px

<ipython-input-44-4b2405318d66>:7: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
  from pandas import datetime


In [29]:
to_date=datetime.now()
start_date = to_date - relativedelta(years=5)
dates = pd.date_range(start_date, to_date)
df = data.DataReader('DELL', 'yahoo', dates[0],dates[-1],)
#df['Date']=df.index
#df.reset_index(inplace=True, drop=True)
df

High        Low        Open       Close     Volume  \
Date                                                                   
2016-08-17   24.363234  23.809525   24.086378   23.809525   137617.0   
2016-08-18   24.363234  23.532669   24.363234   23.671097   895776.0   
2016-08-19   24.086378  23.615725   23.643412   24.086378  2400355.0   
2016-08-22   25.249168  23.588039   23.809525   24.169436  1138322.0   
2016-08-23   25.415281  24.086378   24.224806   24.916945   751657.0   
...                ...        ...         ...         ...        ...   
2021-05-20   99.089996  97.050003   97.099998   98.610001  1420200.0   
2021-05-21   99.699997  98.309998   99.430000   98.470001  1164100.0   
2021-05-24  100.660004  99.139999   99.309998  100.139999  1853200.0   
2021-05-25  100.940002  99.440002  100.699997   99.510002  2067300.0   
2021-05-26  100.449997  99.360001   99.650002   99.660004  1680800.0   

             Adj Close  
Date                    
2016-08-17   23.809525  
2016-08-18   23.671097  
2016-08-19   24.086378  
2016-08-22   24.169436  
2016-08-23   24.916945  
...                ...  
2021-05-20   98.610001  
2021-05-21   98.470001  
2021-05-24  100.139999  
2021-05-25   99.510002  
2021-05-26   99.660004  

[1202 rows x 6 columns]

In [30]:
df1=df[['Close']]
df1

Close
Date                  
2016-08-17   23.809525
2016-08-18   23.671097
2016-08-19   24.086378
2016-08-22   24.169436
2016-08-23   24.916945
...                ...
2021-05-20   98.610001
2021-05-21   98.470001
2021-05-24  100.139999
2021-05-25   99.510002
2021-05-26   99.660004

[1202 rows x 1 columns]

In [31]:
forecast_out=7
df1['prediction']=df1[['Close']].shift(-forecast_out)
df1

<ipython-input-31-d469938a0bba>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['prediction']=df1[['Close']].shift(-forecast_out)


Close  prediction
Date                              
2016-08-17   23.809525   25.332226
2016-08-18   23.671097   25.636766
2016-08-19   24.086378   25.000000
2016-08-22   24.169436   24.739756
2016-08-23   24.916945   24.086378
...                ...         ...
2021-05-20   98.610001         NaN
2021-05-21   98.470001         NaN
2021-05-24  100.139999         NaN
2021-05-25   99.510002         NaN
2021-05-26   99.660004         NaN

[1202 rows x 2 columns]

In [32]:
X=np.array(df1.drop(['prediction'],1))
X=X[:-forecast_out]
X

array([[23.80952454],
       [23.6710968 ],
       [24.0863781 ],
       ...,
       [96.40000153],
       [98.43000031],
       [98.38999939]])

In [33]:
Y=np.array(df1['prediction'])
Y=Y[:-forecast_out]
Y

array([ 25.3322258 ,  25.63676643,  25.        , ..., 100.13999939,
        99.51000214,  99.66000366])

In [34]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.3)

In [35]:
svr_rbf=SVR(kernel='rbf',C=1e3,gamma=0.1)
svr_rbf.fit(x_train,y_train)

SVR(C=1000.0, gamma=0.1)

In [36]:
svm_confidence=svr_rbf.score(x_test,y_test)
svm_confidence


0.9584514289699991

In [58]:
a=[]
b=[]
for i in range(len(y_test)):
    a.append(x_test[i][0])
    b.append(y_test[i])
#gr={'Actual':a,'Predicted':b}
#gr1=pd.DataFrame(gr)
#figure2 = px.line(gr1,template='simple_white')
#figure2.update_layout(xaxis_title="index",yaxis_title="Stock Price")
#figure2.update_xaxes(rangeslider_visible=True)
#figure2.show()
a

[41.395347595214844,
 44.99446487426758,
 28.8700008392334,
 53.30010986328125,
 47.709999084472656,
 74.06999969482422,
 31.959999084472656,
 57.290000915527344,
 42.97895812988281,
 55.970001220703125,
 31.035436630249023,
 66.1500015258789,
 46.937984466552734,
 57.5858268737793,
 36.88261413574219,
 42.22037887573242,
 52.44186019897461,
 40.177188873291016,
 40.919158935546875,
 51.0099983215332,
 33.665557861328125,
 50.369998931884766,
 39.81174087524414,
 50.380001068115234,
 71.52999877929688,
 72.7300033569336,
 56.63999938964844,
 44.45736312866211,
 30.016611099243164,
 52.77000045776367,
 30.43743133544922,
 40.39313507080078,
 39.72314453125,
 65.0,
 35.99114227294922,
 47.68000030517578,
 49.459999084472656,
 54.623477935791016,
 24.08637809753418,
 32.56367874145508,
 35.919158935546875,
 54.20000076293945,
 39.79999923706055,
 38.31672286987305,
 26.15725326538086,
 35.43743133544922,
 51.86600112915039,
 48.150001525878906,
 28.682170867919922,
 51.68000030517578,
 70

In [38]:
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [39]:
lr_confidence=lr.score(x_test,y_test)
lr_confidence


0.952681091036051

In [40]:
x_forecast=np.array(df1.drop(['prediction'],1))[-forecast_out:]
x_forecast

array([[ 98.15000153],
       [ 96.80000305],
       [ 98.61000061],
       [ 98.47000122],
       [100.13999939],
       [ 99.51000214],
       [ 99.66000366]])

In [41]:
lr_pre=lr.predict(x_forecast)
lr_pre

array([ 98.65636524,  97.3050637 ,  99.11680833,  98.97667381,
       100.64828391, 100.01767857, 100.16782488])

In [42]:
svr_rbf_pre=svr_rbf.predict(x_forecast)
svr_rbf_pre

array([ 99.17087469,  96.80186925,  99.9563841 ,  99.74735167,
        99.33957855, 100.22844878, 100.07609603])